name: Build Frontend Assets
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Install Node.js and npm
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Build minified JS files
        run: |
          cd scripts
          python minifier.py --working_dir ../chat_client/static/js --processing_pattern '.*\.js$' --skipping_pattern '.*\.min\.js$' --skip_dirs build

      - name: Build minified CSS files
        run: |
          cd scripts
          python minifier.py --working_dir ../chat_client/static/css --processing_pattern '.*\.css$' --skipping_pattern '.*\.min\.css$' --skip_dirs build

      - name: Push Updated assets
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Added built frontend assets
