# This workflow will generate a release distribution and upload it to PyPI

name: Publish Build and GitHub Release
on:
  push:
    branches:
      - master

jobs:
  build-artifacts:
    uses: ./.github/workflows/build_artifacts.yml
  bump-dynamic-dependencies:
    uses: ./.github/workflows/bump_dynamic_dependencies.yml
    needs: build-artifacts
  build-nano-assets:
    uses: ./.github/workflows/build_nano_assets.yml
    needs: bump-dynamic-dependencies
  tag_release:
    needs: build-nano-assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Version
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{env.VERSION}}
  build_and_publish_docker:
    needs: tag_release
    uses: neongeckocom/.github/.github/workflows/publish_docker.yml@master
    secrets: inherit
    with:
      fetch_depth: 0
