# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'chat_client/version.py'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'LICENSE.md'

jobs:
  build-artifacts:
    uses: ./.github/workflows/build_artifacts.yml
  bump-dynamic-dependencies:
    uses: ./.github/workflows/bump_dynamic_dependencies.yml
  build-nano-assets:
    uses: ./.github/workflows/build_nano_assets.yml
  publish_alpha_release:
    needs: build-artifacts
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@master
    secrets: inherit
    with:
      version_file: "chat_client/version.py"
      setup_py: "setup.py"
      publish_prerelease: True
      publish_pypi: False
      update_changelog: True
  build_and_publish_docker:
    needs: publish_alpha_release
    uses: neongeckocom/.github/.github/workflows/publish_docker.yml@master
    secrets: inherit
    with:
      fetch_depth: 0
