name: Run Unit Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
    with:
      python_version: "3.8"
  docker_build_tests:
    uses: neongeckocom/.github/.github/workflows/docker_build_tests.yml@master
